apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pytorch-training
spec:
  restartPolicy: OnFailure
  containers:
    - name: pytorch-training
      image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.0.1-gpu-py310-cu118-ubuntu20.04-ec2
      command:
        - '/bin/sh'
        - '-c'
      args:
        - 'git clone https://github.com/pytorch/examples.git && python examples/mnist/main.py --no-cuda'
      env:
        - name: OMP_NUM_THREADS
          value: '36'
        - name: KMP_AFFINITY
          value: 'granularity=fine,verbose,compact,1,0'
        - name: KMP_BLOCKTIME
          value: '1'
      resources:
        limits:
          nvidia.com/gpu: 1
  tolerations:
    - key: 'nvidia.com/gpu'
      operator: 'Equal'
      value: 'true'
      effect: 'NoSchedule'
