apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-vectoradd
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: nvidia/samples:vectoradd-cuda11.6.0-ubi8
      resources:
        limits:
          nvidia.com/gpu: 1
  tolerations:
    - key: 'nvidia.com/gpu'
      operator: 'Equal'
      value: 'true'
      effect: 'NoSchedule'
